### ISSUE TITLE
Errors after "git init"

### ISSUE THREAD

**Issue by eddy147** [jzp74/simple-git-prompt#1]
I noticed errors after git init.

Reproduce steps:

- have a code base (not under git yet)
- git init

Expected:
Git prompt, but no errors.

Actual:
```@host /path/to/repo --> git init .
Initialized empty Git repository in /path/to/repo/.git/
bash: [: on: integer expression expected
bash: [: master: integer expression expected
bash: [: _NO_REMOTE_TRACKING_: integer expression expected
bash: [: ^: integer expression expected
```

No errors when browsing non-git folders
Error goes away after git commit.

**Comment by jzp74** [comment]
Apologies for my late response. Issue should be fixed in current master version.
